// seedMedicalProducts.js
// Run with: node seedMedicalProducts.js

import { initializeApp } from 'firebase/app'
import { getFirestore, collection, addDoc, Timestamp } from 'firebase/firestore'

const firebaseConfig = {
  apiKey: 'AIzaSyCHPn-jMxmflg2cJPccFFue8o1SpSzVyNM',
  authDomain: 'onway-f5999.firebaseapp.com',
  projectId: 'onway-f5999',
  storageBucket: 'onway-f5999.firebasestorage.app',
  messagingSenderId: '40420149902',
  appId: '1:40420149902:web:8fcfcb3279f0ade03a97df',
  measurementId: 'G-8F47CPBZD8',
}

const app = initializeApp(firebaseConfig)
const db = getFirestore(app)

const medicalProducts = [
  {
    name: 'Paracetamol 500mg',
    brand: 'Calpol',
    manufacturer: 'GSK Pharmaceuticals',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '500mg',
    composition: 'Paracetamol 500mg',
    packSize: 'Strip of 15 Tablets',
    prescriptionRequired: false,
    price: 22,
    originalPrice: 25,
    stock: 500,
    rating: 4.5,
    reviews: 1240,
    deliveryTime: 15,
    description: 'Paracetamol 500mg is used for relief of mild to moderate pain and fever. Suitable for adults and children over 12 years.',
    sideEffects: 'Rare: skin rash, liver damage on overdose',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Amoxicillin 500mg',
    brand: 'Mox',
    manufacturer: 'Ranbaxy Laboratories',
    category: 'medicines',
    dosageForm: 'Capsule',
    strength: '500mg',
    composition: 'Amoxicillin Trihydrate 500mg',
    packSize: 'Strip of 10 Capsules',
    prescriptionRequired: true,
    price: 85,
    originalPrice: 95,
    stock: 300,
    rating: 4.3,
    reviews: 876,
    deliveryTime: 20,
    description: 'Amoxicillin is a penicillin antibiotic used to treat bacterial infections including chest infections, dental abscesses, and urinary tract infections.',
    sideEffects: 'Diarrhea, nausea, skin rash, allergic reaction',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Cetirizine 10mg',
    brand: 'Zyrtec',
    manufacturer: 'UCB India Pvt Ltd',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '10mg',
    composition: 'Cetirizine Hydrochloride 10mg',
    packSize: 'Strip of 10 Tablets',
    prescriptionRequired: false,
    price: 35,
    originalPrice: 40,
    stock: 400,
    rating: 4.4,
    reviews: 654,
    deliveryTime: 15,
    description: 'Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching, and sneezing.',
    sideEffects: 'Drowsiness, dry mouth, headache',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Omeprazole 20mg',
    brand: 'Omez',
    manufacturer: 'Dr. Reddy\'s Laboratories',
    category: 'medicines',
    dosageForm: 'Capsule',
    strength: '20mg',
    composition: 'Omeprazole 20mg',
    packSize: 'Strip of 10 Capsules',
    prescriptionRequired: false,
    price: 55,
    originalPrice: 65,
    stock: 350,
    rating: 4.6,
    reviews: 980,
    deliveryTime: 15,
    description: 'Omeprazole reduces the amount of acid produced in the stomach. Used for acid reflux, GERD, stomach ulcers, and heartburn.',
    sideEffects: 'Headache, diarrhea, nausea, stomach pain',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Metformin 500mg',
    brand: 'Glycomet',
    manufacturer: 'USV Pvt Ltd',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '500mg',
    composition: 'Metformin Hydrochloride 500mg',
    packSize: 'Strip of 20 Tablets',
    prescriptionRequired: true,
    price: 30,
    originalPrice: 35,
    stock: 600,
    rating: 4.5,
    reviews: 1100,
    deliveryTime: 20,
    description: 'Metformin is used to treat type 2 diabetes. It helps control blood sugar levels and is often used alongside diet and exercise.',
    sideEffects: 'Nausea, vomiting, diarrhea, stomach upset',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Azithromycin 500mg',
    brand: 'Azithral',
    manufacturer: 'Alembic Pharmaceuticals',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '500mg',
    composition: 'Azithromycin 500mg',
    packSize: 'Strip of 3 Tablets',
    prescriptionRequired: true,
    price: 95,
    originalPrice: 110,
    stock: 250,
    rating: 4.4,
    reviews: 720,
    deliveryTime: 20,
    description: 'Azithromycin is a macrolide antibiotic used to treat bacterial infections including respiratory infections, skin infections, and ear infections.',
    sideEffects: 'Nausea, diarrhea, stomach pain, vomiting',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Ibuprofen 400mg',
    brand: 'Brufen',
    manufacturer: 'Abbott India Ltd',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '400mg',
    composition: 'Ibuprofen 400mg',
    packSize: 'Strip of 15 Tablets',
    prescriptionRequired: false,
    price: 28,
    originalPrice: 32,
    stock: 450,
    rating: 4.3,
    reviews: 890,
    deliveryTime: 15,
    description: 'Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used to relieve pain, reduce fever, and decrease inflammation.',
    sideEffects: 'Stomach upset, nausea, heartburn, dizziness',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Vitamin D3 60000 IU',
    brand: 'D-Rise',
    manufacturer: 'Sun Pharmaceutical Industries',
    category: 'medicines',
    dosageForm: 'Capsule',
    strength: '60000 IU',
    composition: 'Cholecalciferol (Vitamin D3) 60000 IU',
    packSize: 'Pack of 4 Capsules',
    prescriptionRequired: false,
    price: 120,
    originalPrice: 140,
    stock: 300,
    rating: 4.7,
    reviews: 1560,
    deliveryTime: 15,
    description: 'Vitamin D3 supplement used to treat and prevent Vitamin D deficiency. Supports bone health, immune function, and calcium absorption.',
    sideEffects: 'Rare: nausea, weakness, frequent urination on overdose',
    returnDays: 7,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Pantoprazole 40mg',
    brand: 'Pan-D',
    manufacturer: 'Alkem Laboratories',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '40mg',
    composition: 'Pantoprazole 40mg + Domperidone 10mg',
    packSize: 'Strip of 10 Tablets',
    prescriptionRequired: false,
    price: 65,
    originalPrice: 75,
    stock: 380,
    rating: 4.5,
    reviews: 830,
    deliveryTime: 15,
    description: 'Pantoprazole + Domperidone combination used to treat acidity, heartburn, and gastroesophageal reflux disease (GERD).',
    sideEffects: 'Headache, diarrhea, dry mouth, dizziness',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
  {
    name: 'Montelukast 10mg',
    brand: 'Montair',
    manufacturer: 'Cipla Ltd',
    category: 'medicines',
    dosageForm: 'Tablet',
    strength: '10mg',
    composition: 'Montelukast Sodium 10mg',
    packSize: 'Strip of 10 Tablets',
    prescriptionRequired: true,
    price: 110,
    originalPrice: 125,
    stock: 200,
    rating: 4.4,
    reviews: 540,
    deliveryTime: 20,
    description: 'Montelukast is used to prevent and treat asthma and to relieve symptoms of seasonal allergies. It works by blocking leukotrienes.',
    sideEffects: 'Headache, stomach pain, tiredness, fever',
    returnDays: 0,
    warranty: null,
    imageUrl: 'https://res.cloudinary.com/demo/image/upload/v1/samples/medicine-placeholder.jpg',
  },
]

async function seedProducts() {
  console.log('🚀 Starting to seed medical products...\n')
  let successCount = 0

  for (const product of medicalProducts) {
    try {
      const productId = `med_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`
      const docRef = await addDoc(collection(db, 'products'), {
        ...product,
        id: productId,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      })
      console.log(`✅ Added: ${product.name} (doc: ${docRef.id})`)
      successCount++
      // Small delay to avoid rate limiting
      await new Promise(r => setTimeout(r, 200))
    } catch (error) {
      console.error(`❌ Failed to add ${product.name}:`, error.message)
    }
  }

  console.log(`\n🎉 Done! ${successCount}/${medicalProducts.length} products added successfully.`)
  process.exit(0)
}

seedProducts()
